cmake_minimum_required(VERSION 3.22.1)
project(packetcapture C)
add_library(zdtun SHARED zdtun/zdtun.c zdtun/utils.c)
target_compile_definitions(zdtun PRIVATE ANDROID NO_DEBUG)
target_include_directories(zdtun PUBLIC zdtun)
target_link_libraries(zdtun log)
add_library(capture_jni SHARED capture_jni.c)
target_link_libraries(capture_jni zdtun log android)
target_compile_options(capture_jni PRIVATE -Wall -Wextra -Werror=implicit-function-declaration)
